package com.personal.aws.dynamodb.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "Music")
public class Music {

    @DynamoDBHashKey(attributeName="Artist")
    /*@DynamoDBAutoGeneratedKey*/
    private String artist;

    @DynamoDBRangeKey(attributeName = "SongTitle")
    private String songTitle;

    @DynamoDBAttribute(attributeName = "AlbumTitle")
    private String albumTitle;

    @DynamoDBAttribute(attributeName = "Awards")
    private Integer awards;
}
